import {
  clean,
  number,
  pickleString,
} from "@/lib/material-models/pickle-utils";

export function abaqusLibraryFileName(projectName) {
  return `${clean(projectName, "Composite_Project")}_materials.lib`;
}

export function buildMaterialData(inputs, model) {
  const p = model.properties;
  const name = clean(inputs.name, "Composite_Material");
  const parts = [
    `'materialIdentifier': ''`,
    `'description': 'Generated by JSCR Composite Property Calculator; N-mm-MPa-tonne units'`,
  ];
  if (p.density.value !== null)
    parts.push(`'density': {'temperatureDependency': OFF, 'dependencies': 0, 'table': ((${number(p.density.value * 1e-12)},),), 'distributionType': UNIFORM, 'fieldName': ''}`);
  const elastic = [p.E1, p.E2, p.E3, p.nu12, p.nu13, p.nu23, p.G12, p.G13, p.G23];
  if (elastic.every((item) => item.value !== null))
    parts.push(`'elastic': {'temperatureDependency': OFF, 'moduli': LONG_TERM, 'noCompression': OFF, 'noTension': OFF, 'dependencies': 0, 'table': ((${elastic.map((item) => number(item.value)).join(", ")}),), 'type': ENGINEERING_CONSTANTS}`);
  if ([p.alpha1, p.alpha2, p.alpha3].every((item) => item.value !== null))
    parts.push(`'expansion': {'temperatureDependency': OFF, 'dependencies': 0, 'table': ((${[p.alpha1, p.alpha2, p.alpha3].map((item) => number(item.value * 1e-6)).join(", ")}),), 'type': ORTHOTROPIC, 'zero': 0.0}`);
  if (p.cp.value !== null)
    parts.push(`'specificHeat': {'temperatureDependency': OFF, 'dependencies': 0, 'table': ((${number(p.cp.value * 1e6)},),)}`);
  parts.push(`'name': '${name}'`);
  return `{${parts.join(", ")}}`;
}

export function generateAbaqus2020Library(inputs, model, projectName) {
  const materialName = clean(inputs.name, "Composite_Material");
  const fileName = abaqusLibraryFileName(projectName);
  const data = buildMaterialData(inputs, model);
  const now = Date.now() / 1000;
  return `((I0\nI-1\n${pickleString(fileName)}I0\n(dp0\ntp1\n(I1\nI0\n${pickleString(materialName)}I1\n(dp2\n${pickleString("Data Source")}${pickleString("Generated by JSCR Composite Property Calculator")}s${pickleString("Description")}${pickleString("Generated composite engineering constants; N-mm-MPa-tonne units")}s${pickleString("Time Stamp")}F${now}\ns${pickleString("visible")}(lp3\n${pickleString("Data Source")}a${pickleString("Description")}a${pickleString("Units")}a${pickleString("Vendor material name")}as${pickleString("version")}${pickleString("2020")}s${pickleString("Vendor material name")}${pickleString(materialName)}s${pickleString("Units")}${pickleString("N, mm, MPa, tonne")}s${pickleString("Data")}${pickleString(data)}stp4\ntp5\n.`;
}
