import { clean, number, pickleString, table } from "@/lib/material-models/pickle-utils";

export function abaqusLibraryFileName(projectName) {
  return `${clean(projectName, "CDP_Project")}_materials.lib`;
}

// Abaqus/CAE libraries use a private Python pickle layout. This targets the
// Abaqus 2020 layout verified against the CAE-created library supplied by JSCR.
export function generateAbaqus2020Library(inputs, model, projectName) {
  const materialName = clean(inputs.name, "CDP_Material");
  const fileName = abaqusLibraryFileName(projectName);
  const compressionHardening = table(model.compression, (point) => point.stress);
  const compressionDamage = table(model.compression, (point) => point.damage);
  const tensionStiffening = table(model.tension, (point) => point.stress);
  const tensionDamage = table(model.tension, (point) => point.damage);
  const density = inputs.density * 1e-12;
  const data = `{'concreteDamagedPlasticity': {'temperatureDependency': OFF, 'concreteCompressionDamage': {'temperatureDependency': OFF, 'table': ${compressionDamage}, 'dependencies': 0, 'tensionRecovery': 0.0}, 'concreteCompressionHardening': {'temperatureDependency': OFF, 'table': ${compressionHardening}, 'rate': OFF, 'dependencies': 0}, 'concreteTensionStiffening': {'temperatureDependency': OFF, 'table': ${tensionStiffening}, 'rate': OFF, 'dependencies': 0, 'type': DISPLACEMENT}, 'dependencies': 0, 'concreteTensionDamage': {'temperatureDependency': OFF, 'table': ${tensionDamage}, 'dependencies': 0, 'compressionRecovery': 1.0, 'type': DISPLACEMENT}, 'table': ((${number(inputs.dilation)}, ${number(inputs.eccentricity)}, ${number(inputs.fb0fc0)}, ${number(inputs.k)}, ${number(inputs.viscosity)}),)}, 'materialIdentifier': '', 'description': 'Generated by JSCR CDP Calculator; N-mm-MPa-tonne units', 'density': {'temperatureDependency': OFF, 'dependencies': 0, 'table': ((${number(density)},),), 'distributionType': UNIFORM, 'fieldName': ''}, 'elastic': {'temperatureDependency': OFF, 'moduli': LONG_TERM, 'noCompression': OFF, 'noTension': OFF, 'dependencies': 0, 'table': ((${number(inputs.E)}, ${number(inputs.nu)}),), 'type': ISOTROPIC}, 'name': '${materialName}'}`;
  const now = Date.now() / 1000;

  return `((I0\nI-1\n${pickleString(fileName)}I0\n(dp0\ntp1\n(I1\nI0\n${pickleString(materialName)}I1\n(dp2\n${pickleString("Data Source")}${pickleString("Generated by JSCR CDP Calculator")}s${pickleString("Description")}${pickleString("Generated CDP material; N-mm-MPa-tonne units")}s${pickleString("Time Stamp")}F${now}\ns${pickleString("visible")}(lp3\n${pickleString("Data Source")}a${pickleString("Description")}a${pickleString("Units")}a${pickleString("Vendor material name")}as${pickleString("version")}${pickleString("2020")}s${pickleString("Vendor material name")}${pickleString(materialName)}s${pickleString("Units")}${pickleString("N, mm, MPa, tonne")}s${pickleString("Data")}${pickleString(data)}stp4\ntp5\n.`;
}
