import {Player} from './game/player.js';import {MAX_LIVES,loseHeart} from './game/lifeSystem.js';import {escapeTrapX} from './game/trapSystem.js';import {World} from './game/world.js';import {makeQuestion,makeCustomQuestion,validateAnswer,explain,maxForGrade} from './math/mathEngine.js';import {stages,getStage,getAchievement,getBlessing} from './data/stages.js';import {makeKnowledgeQuestion,checkQuiz,KNOWLEDGE_TOTAL} from './quiz/quizEngine.js';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),keys={};let selectedStage=getStage(new URLSearchParams(location.search).get('stage')||localStorage.getItem('luma-selected-stage')||1);const world=new World(selectedStage.id),player=new Player(world.level.spawn),mahiSprite=new Image(),sentinelSprite=new Image(),villainSprite=new Image(),advancedSprite=new Image();mahiSprite.src='assets/mahi-sprite-sheet.png';sentinelSprite.src='assets/moonstone-sentinel-sheet.png';villainSprite.src='assets/ember-moss-villains-sheet.png';advancedSprite.src='assets/advanced-creatures-sheet.png';let started=false,paused=false,last=0,camera=0,checkpoint=world.level.spawn,checkpointLit=false,collected=new Set(),stats={attempts:0,correct:0,start:0,score:0,streak:0,bestStreak:0,lives:MAX_LIVES,kCorrect:0,kAttempts:0},question=null,challenge=0,challengeMode='gate',activeEnemy=null,celebrateUntil=0,activeCore=null,activeTrap=null;
const KNOW_KEY='mahi-knowledge',SAVE_KEY='mahi-save-'+selectedStage.id;let knowledgeLearned=new Set((()=>{try{return JSON.parse(localStorage.getItem(KNOW_KEY))||[]}catch{return[]}})()),knowledgeSeen=new Set();
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="src/coins-glitter.css">');const COIN_KEY='mahi-gold-coins',RING_KEY='mahi-golden-rings';let goldCoins=Number(localStorage.getItem(COIN_KEY)||0),goldenRings=Number(localStorage.getItem(RING_KEY)||0);$('#coins').textContent=`🪙 ${goldCoins}`;$('#rings').textContent=`◎ ${goldenRings}`;
function saveKnowledge(){localStorage.setItem(KNOW_KEY,JSON.stringify([...knowledgeLearned]))}
function updateKnowHud(){$('#know').textContent=`🧠 ${knowledgeLearned.size} / ${KNOWLEDGE_TOTAL}`}
function saveSnapshot(){const op=stageOpponent();const snap={x:player.x,y:player.y,score:stats.score,lives:stats.lives,streak:stats.streak,bestStreak:stats.bestStreak,kCorrect:stats.kCorrect,attempts:stats.attempts,correct:stats.correct,collected:[...collected],checkpointLit,checkpoint,gateOpen:world.gateOpen,cores:(world.level.cores||[]).filter(c=>c.done).map(c=>c.id),enemy:op?{cleared:!!op.cleared,lights:op.lights}:null};try{localStorage.setItem(SAVE_KEY,JSON.stringify(snap));caption('★ Progress saved — reload this stage to resume here.')}catch{caption('Could not save progress.')}}
function restoreSnapshot(){let s;try{s=JSON.parse(localStorage.getItem(SAVE_KEY))}catch{}if(!s)return;player.x=s.x;player.y=s.y;player.vx=0;player.vy=0;Object.assign(stats,{score:s.score??0,lives:Math.min(MAX_LIVES,s.lives??MAX_LIVES),streak:s.streak??0,bestStreak:s.bestStreak??0,kCorrect:s.kCorrect??0,attempts:s.attempts??0,correct:s.correct??0});collected=new Set(s.collected||[]);if(s.checkpointLit){checkpointLit=true;checkpoint=s.checkpoint||checkpoint}world.gateOpen=!!s.gateOpen;for(const c of world.level.cores||[])if((s.cores||[]).includes(c.id))c.done=true;const op=stageOpponent();if(op&&s.enemy){op.cleared=s.enemy.cleared;op.lights=s.enemy.lights}updateLives();updateKnowHud();$('#score').textContent=`★ ${stats.score}`;$('#gems').textContent=`✦ ${collected.size} / 3`;setTimeout(()=>caption('Resumed from your saved point.'),400)}
const QICONS={
 abacus:'<svg viewBox="0 0 48 48" fill="none" stroke="#ffe08a" stroke-width="2"><rect x="6" y="8" width="36" height="32" rx="2"/><line x1="6" y1="19" x2="42" y2="19"/><line x1="6" y1="30" x2="42" y2="30"/><g fill="#ffe08a" stroke="none"><circle cx="14" cy="13.5" r="3"/><circle cx="22" cy="13.5" r="3"/><circle cx="34" cy="13.5" r="3"/><circle cx="16" cy="24.5" r="3"/><circle cx="30" cy="24.5" r="3"/><circle cx="12" cy="35.5" r="3"/><circle cx="20" cy="35.5" r="3"/><circle cx="38" cy="35.5" r="3"/></g></svg>',
 napier:'<svg viewBox="0 0 48 48" fill="none" stroke="#ffe08a" stroke-width="2"><rect x="8" y="8" width="32" height="32"/><line x1="18" y1="8" x2="18" y2="40"/><line x1="28" y1="8" x2="28" y2="40"/><line x1="8" y1="18" x2="40" y2="18"/><line x1="8" y1="28" x2="40" y2="28"/><path d="M8 18l10 10M18 8l10 10M28 18l10 10M18 28l10 10" stroke-width="1.3"/></svg>',
 pascal:'<svg viewBox="0 0 48 48" fill="none" stroke="#ffe08a" stroke-width="2"><rect x="6" y="14" width="36" height="20" rx="2"/><circle cx="14" cy="24" r="4"/><circle cx="24" cy="24" r="4"/><circle cx="34" cy="24" r="4"/><path d="M14 20v4M24 20v4M34 20v4"/></svg>',
 gears:'<svg viewBox="0 0 48 48" fill="none" stroke="#ffe08a" stroke-width="2"><circle cx="19" cy="21" r="8"/><circle cx="19" cy="21" r="2.5" fill="#ffe08a"/><path d="M19 9v4M19 29v4M7 21h4M27 21h4M11 13l3 3M27 26l-3-3M27 16l-3 3M11 29l3-3" stroke-width="3"/><circle cx="34" cy="33" r="5"/></svg>',
 engine:'<svg viewBox="0 0 48 48" fill="none" stroke="#ffe08a" stroke-width="2"><rect x="10" y="6" width="28" height="36" rx="2"/><line x1="10" y1="16" x2="38" y2="16"/><line x1="10" y1="26" x2="38" y2="26"/><g stroke="none" fill="#ffe08a"><circle cx="17" cy="11" r="1.6"/><circle cx="24" cy="11" r="1.6"/><circle cx="31" cy="11" r="1.6"/><circle cx="17" cy="21" r="1.6"/><circle cx="24" cy="21" r="1.6"/><circle cx="31" cy="21" r="1.6"/></g></svg>',
 punchcard:'<svg viewBox="0 0 48 48" fill="none" stroke="#ffe08a" stroke-width="2"><path d="M10 10h22l6 6v22H10z"/><g fill="#ffe08a" stroke="none"><rect x="14" y="20" width="4" height="3"/><rect x="21" y="20" width="4" height="3"/><rect x="28" y="20" width="4" height="3"/><rect x="14" y="27" width="4" height="3"/><rect x="28" y="27" width="4" height="3"/></g></svg>',
 room:'<svg viewBox="0 0 48 48" fill="none" stroke="#ffe08a" stroke-width="2"><rect x="6" y="10" width="16" height="30"/><rect x="26" y="10" width="16" height="30"/><path d="M9 16h10M9 21h10M29 16h10M29 21h10" stroke-width="1.5"/><circle cx="14" cy="32" r="2.5"/><circle cx="34" cy="32" r="2.5"/></svg>',
 tube:'<svg viewBox="0 0 48 48" fill="none" stroke="#ffe08a" stroke-width="2"><path d="M18 8h12v18a6 6 0 0 1-12 0z"/><path d="M20 40v-6M28 40v-6M24 40v-8"/><path d="M20 15c2 3 6 3 8 0" stroke-width="1.5"/></svg>',
 transistor:'<svg viewBox="0 0 48 48" fill="none" stroke="#ffe08a" stroke-width="2"><path d="M16 12a12 12 0 0 1 0 24z" fill="#ffe08a" stroke="none"/><path d="M16 24H8M28 24h12M28 24l8-7M28 24l8 7"/></svg>',
 chip:'<svg viewBox="0 0 48 48" fill="none" stroke="#ffe08a" stroke-width="2"><rect x="14" y="14" width="20" height="20" rx="2"/><path d="M14 20H8M14 28H8M40 20h-6M40 28h-6M20 14V8M28 14V8M20 40v-6M28 40v-6"/><circle cx="24" cy="24" r="3" fill="#ffe08a" stroke="none"/></svg>',
 file:'<svg viewBox="0 0 48 48" fill="none" stroke="#ffe08a" stroke-width="2"><path d="M14 6h14l8 8v28H14z"/><path d="M28 6v8h8"/><line x1="19" y1="24" x2="31" y2="24"/><line x1="19" y1="30" x2="31" y2="30"/></svg>',
 folder:'<svg viewBox="0 0 48 48" fill="none" stroke="#ffe08a" stroke-width="2"><path d="M8 14h12l4 4h16v20a2 2 0 0 1-2 2H10a2 2 0 0 1-2-2z"/></svg>'
};
addEventListener('keydown',e=>{if(e.ctrlKey&&(e.code==='Digit7'||e.code==='Numpad7')){e.preventDefault();e.stopPropagation();cheatManualQuestion();return}if(e.ctrlKey&&e.code==='KeyS'){e.preventDefault();e.stopPropagation();saveSnapshot();return}keys[e.code]=true;if(['ArrowUp','ArrowDown','Space'].includes(e.code))e.preventDefault();if(e.code==='Escape')paused=!paused});addEventListener('keyup',e=>keys[e.code]=false);
for(const b of document.querySelectorAll('#touch button')){const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();keys[k]=true};b.onpointerup=b.onpointercancel=()=>keys[k]=false}
function decorateCompletion(){const achievement=getAchievement(selectedStage.id),report=$('#report'),summary=report.textContent;$('#completeTitle').textContent=selectedStage.id===10?'The Throne of Learning is restored!':`Achievement unlocked: ${achievement.title}`;$('#guruWish').textContent=`“${getBlessing(selectedStage.id)}”`;report.innerHTML=`<span class="achievement-title">${achievement.title}</span><span class="achievement-story">${achievement.story}</span><br><br>${summary}`;$('#complete .card').classList.toggle('finale',selectedStage.id===10);$('#keeperReveal').classList.toggle('hidden',selectedStage.id!==10)}
function modal(id,on){if(id==='#complete'&&on)decorateCompletion();$(id).classList.toggle('hidden',!on)}
function awardCoins(amount){goldCoins+=amount;localStorage.setItem(COIN_KEY,goldCoins);const hud=$('#coins'),burst=$('#coinBurst');hud.textContent=`🪙 ${goldCoins}`;hud.classList.remove('coin-pop');burst.innerHTML=`<span class="coin-main">🪙</span><span class="coin-text">+${amount} gold</span>${Array.from({length:12},(_,i)=>`<i class="glitter" style="--i:${i}"></i>`).join('')}`;burst.classList.remove('hidden');requestAnimationFrame(()=>hud.classList.add('coin-pop'));setTimeout(()=>burst.classList.add('hidden'),1050)}
function awardGoldenRings(amount=1){goldenRings+=amount;localStorage.setItem(RING_KEY,goldenRings);const hud=$('#rings'),layer=$('#ringLayer'),left=Math.max(5,Math.min(95,(player.x-camera+player.w/2)/canvas.width*100)),top=Math.max(15,Math.min(88,(player.y+player.h/2)/canvas.height*100));hud.textContent=`◎ ${goldenRings}`;hud.classList.remove('ring-pop');layer.innerHTML=`${Array.from({length:3},(_,i)=>`<i class="golden-ring" style="--i:${i};left:${left}%;top:${top}%"></i>`).join('')}<strong class="ring-reward-label" style="left:${left}%;top:${top}%">+${amount} GOLDEN RING</strong>`;requestAnimationFrame(()=>hud.classList.add('ring-pop'));setTimeout(()=>layer.innerHTML='',1300)}
function updateScore(correct){if(correct){stats.streak++;stats.bestStreak=Math.max(stats.bestStreak,stats.streak);stats.score+=100*Math.min(stats.streak,5);awardCoins(Math.min(stats.streak,5));awardGoldenRings()}else stats.streak=0;$('#score').textContent=`★ ${stats.score}`;$('#streak').textContent=`🔥 ${stats.streak}`;$('#streak').classList.remove('hot');requestAnimationFrame(()=>$('#streak').classList.toggle('hot',stats.streak>1))}
function updateLives(){const lives=$('#lives');lives.textContent='♥'.repeat(stats.lives)+'♡'.repeat(MAX_LIVES-stats.lives);lives.setAttribute('aria-label',`${stats.lives} lives remaining`);lives.classList.remove('life-hit');requestAnimationFrame(()=>lives.classList.add('life-hit'))}
function loseLife(){const result=loseHeart(stats.lives);stats.lives=result.lives;updateLives();if(!result.restartStage)return true;localStorage.removeItem(SAVE_KEY);modal('#mathPanel',false);hideConfrontation();paused=true;$('#lifeResetTitle').textContent='Four hearts used—restart this stage!';$('#lifeResetMessage').textContent=`Mahi returns to the beginning of Stage ${selectedStage.id} with four fresh hearts. Keep going—you are learning every time!`;modal('#lifeReset',true);setTimeout(()=>location.href=`?stage=${selectedStage.id}`,2800);return false}
function renderBattleLights(){if(!activeEnemy)return;$('#battleLights').innerHTML=[0,1,2].map(i=>`<i class="${i<activeEnemy.lights?'on':'lost'}"></i>`).join('');if(activeEnemy.lights<3){const fighter=$('#opponentFighter');fighter.classList.remove('correct-hit');requestAnimationFrame(()=>fighter.classList.add('correct-hit'));setTimeout(()=>fighter.classList.remove('correct-hit'),520)}}
function showConfrontation(enemy){const fighter=$('#opponentFighter');fighter.className=`fighter opponent-fighter ${enemy.kind}`;fighter.style='';if(['frost','storm','beetle','voidcat'].includes(enemy.kind)){const offsets={frost:0,storm:2,beetle:4,voidcat:6};fighter.style.backgroundImage="url('assets/advanced-creatures-sheet.png')";fighter.style.backgroundSize='800% 100%';fighter.style.backgroundPosition=`${offsets[enemy.kind]*100/7}% 0`}$('#opponentName').textContent=`${enemy.name} • ${enemy.power}`;$('#confrontationScene').classList.remove('hidden');renderBattleLights()}
function hideConfrontation(){$('#confrontationScene').classList.add('hidden');$('#confrontationScene').classList.remove('defeat-flash');$('#opponentFighter').classList.remove('laughing','defeated')}
function showMotivation(done){const messages=stats.streak>=3?['Your careful thinking built a brilliant streak!','You stayed focused through every challenge!','Strong practice is turning into real skill!']:['You kept trying—and that is how minds grow!','Every attempt helped you find the answer!','Courage means trying again. Wonderful work!'];$('#motivationTitle').textContent=`${activeEnemy.name} cleared!`;$('#motivationMessage').textContent=messages[Math.floor(Math.random()*messages.length)];$('#motivationStats').textContent=`★ ${stats.score} points • 🔥 Best streak ${stats.bestStreak}`;$('#motivation').classList.remove('hidden');setTimeout(()=>{$('#motivation').classList.add('hidden');done()},2300)}
function defeatConfrontation(done){stats.score+=500;$('#score').textContent=`★ ${stats.score}`;$('#opponentFighter').classList.add('defeated');$('#confrontationScene').classList.add('defeat-flash');setTimeout(()=>{hideConfrontation();showMotivation(done)},1150)}
function laughConfrontation(){const fighter=$('#opponentFighter');fighter.classList.add('laughing');setTimeout(()=>fighter.classList.remove('laughing'),1300)}
function renderStages(){const box=$('#stagePicker');box.innerHTML='';stages.forEach(s=>{const b=document.createElement('button');b.className=s.id===selectedStage.id?'selected':'';b.textContent=`${s.id}. ${s.name}`;b.onclick=()=>{localStorage.setItem('luma-selected-stage',s.id);location.href=`?stage=${s.id}`};box.append(b)});$('#stageDescription').textContent=`${selectedStage.description} • Route length ${world.level.width}px`;$('#stageLabel').textContent=`Stage ${selectedStage.id}: ${selectedStage.name}`}
renderStages();updateLives();updateKnowHud();restoreSnapshot();function startStage(){modal('#intro',false);started=true;stats.start=performance.now();requestAnimationFrame(loop)}$('#playBtn').onclick=()=>{sessionStorage.setItem('mahi-adventure','1');startStage()};$('#againBtn').onclick=()=>location.reload();$('#nextBtn').onclick=()=>location.href=`?stage=${Math.min(10,selectedStage.id+1)}`;$('#settingsBtn').onclick=()=>{paused=true;modal('#settings',true)};$('#closeSettings').onclick=()=>{modal('#settings',false);paused=false};$('#contrast').onchange=e=>document.body.classList.toggle('contrast',e.target.checked);$('#dyslexia').onchange=e=>document.body.classList.toggle('dyslexia',e.target.checked);
function caption(t){$('#caption').textContent=t;setTimeout(()=>$('#caption').textContent='',1800)}
function beginMath(){challengeMode='gate';paused=true;challenge=0;$('#challengeLabel').textContent='MEMORY GATE';nextQuestion();modal('#mathPanel',true);caption('The memory gate hums: a constellation must be restored.')}
function beginSentinelChallenge(enemy){activeEnemy=enemy;player.facing=enemy.x>=player.x?1:-1;enemy.vx=Math.abs(enemy.vx)*(player.x<enemy.x?-1:1);challengeMode='sentinel';paused=true;challenge=3-enemy.lights;$('#challengeLabel').textContent=`${enemy.name.toUpperCase()} CHALLENGE`;showConfrontation(enemy);nextQuestion();modal('#mathPanel',true);caption(`${enemy.name}: “Halt, explorer! Do you know this one?”`)}
function nextQuestion(){$('#qIcon').innerHTML='';$('#answers').classList.remove('know');const step=Math.min(challenge,2),labels=['Warm-up','Growing','Challenge'],gradeCap=maxForGrade(+$('select').value),limit=Math.min(selectedStage.difficulty[step],gradeCap);question=(Math.random()<.25&&pickCustomQuestion(selectedStage.operation))||makeQuestion(selectedStage.operation,limit);$('#question').textContent=question.prompt;$('#progress').textContent=challengeMode==='sentinel'?`${activeEnemy.name} lights: ${'● '.repeat(activeEnemy.lights)}${'○ '.repeat(3-activeEnemy.lights)} • ${labels[step]} (to ${limit})`:`Stage ${selectedStage.id} • ${labels[step]} • Range to ${limit}`;$('#feedback').textContent=challengeMode==='sentinel'?`${activeEnemy.name}: “Show me what you know!”`:'';$('#hint').textContent='';const box=$('#answers');box.innerHTML='';question.choices.forEach(v=>{const b=document.createElement('button');b.textContent=v;b.onclick=()=>answer(v,b);box.append(b)})}
function answer(v,b){if(question.kind==='knowledge')return answerKnowledge(v,b);if(challengeMode==='trap'){if(validateAnswer(question,v)){b.classList.add('correct');stats.score+=40;awardGoldenRings();$('#score').textContent=`★ ${stats.score}`;$('#feedback').textContent='Correct — golden ring earned! Leap clear!';setTimeout(()=>trapResolve(true),500)}else{b.classList.add('wrong');b.disabled=true;$('#feedback').textContent=`Wrong! ${explain(question)} The trap strikes — one heart lost.`;setTimeout(()=>trapResolve(false),1300)}return}stats.attempts++;if(validateAnswer(question,v)){stats.correct++;challenge++;updateScore(true);b.classList.add('correct');if(challengeMode==='sentinel'){activeEnemy.lights--;renderBattleLights();$('#feedback').textContent=`Correct! +${100*Math.min(stats.streak,5)} points. One light fades.`}else $('#feedback').textContent=`Brilliant! +${100*Math.min(stats.streak,5)} points.`;setTimeout(()=>{if(challengeMode==='sentinel'&&activeEnemy.lights===0){activeEnemy.cleared=true;modal('#mathPanel',false);defeatConfrontation(()=>{paused=false;celebrateUntil=performance.now()+1200;caption(`${activeEnemy.name} dissolves into starlight! +500 points.`)})}else if(challengeMode==='gate'&&challenge===3){serveGateKnowledge()}else nextQuestion()},700)}else{if(!loseLife())return;updateScore(false);b.classList.add('wrong');b.disabled=true;if(challengeMode==='sentinel'){activeEnemy.laughUntil=performance.now()+1300;laughConfrontation();$('#feedback').textContent=`${activeEnemy.name}: “Hee-hee! Not quite!” One heart lost. ${explain(question)} Try again.`}else $('#feedback').textContent=`Almost! One heart lost. ${explain(question)} Choose again.`}}
$('#hintBtn').onclick=()=>{if(question.kind==='knowledge'){$('#hint').textContent=`This fact comes from the topic: ${question.topic}. Read every option carefully.`;return}$('#hint').textContent=question.operation==='multiplication'?`Hint: count ${question.b}, ${question.a} times.`:`Hint: start at ${question.a} and ${question.operation==='addition'?'count up':'count back'} ${question.b}.`};
function paintKnowledge(){const q=question;$('#qIcon').innerHTML=q.icon&&QICONS[q.icon]?QICONS[q.icon]:'';$('#question').textContent=q.prompt;$('#progress').textContent=`Evolution of Computers • ${q.topic}`;$('#hint').textContent='';const box=$('#answers');box.classList.add('know');box.innerHTML='';q.choices.forEach(v=>{const b=document.createElement('button');b.className='know-choice';b.textContent=v;b.onclick=()=>answer(v,b);box.append(b)})}
function beginKnowledgeChallenge(core){activeCore=core;challengeMode='knowledge';paused=true;$('#challengeLabel').textContent='DATA CORE';question=makeKnowledgeQuestion(new Set([...knowledgeLearned,...knowledgeSeen]));knowledgeSeen.add(question.id);paintKnowledge();$('#feedback').textContent='A fact from the Evolution of Computers. No hearts are lost here — think it through.';modal('#mathPanel',true);caption('A Data Core hums with knowledge from the chapter.')}
function serveGateKnowledge(){challengeMode='gate-knowledge';$('#challengeLabel').textContent='KNOWLEDGE GATE';question=makeKnowledgeQuestion(new Set([...knowledgeSeen]));knowledgeSeen.add(question.id);paintKnowledge();$('#feedback').textContent='Answer one fact from the chapter to open the gate.'}
function answerKnowledge(v,b){stats.kAttempts++;const ok=checkQuiz(question,v);if(challengeMode==='trap'){if(ok){stats.kCorrect++;stats.score+=40;awardGoldenRings();$('#score').textContent=`★ ${stats.score}`;if(!knowledgeLearned.has(question.id)){knowledgeLearned.add(question.id);saveKnowledge();updateKnowHud()}b.classList.add('correct');$('#feedback').textContent=`✔ ${question.fact} — leap clear!`;setTimeout(()=>trapResolve(true),800)}else{b.classList.add('wrong');b.disabled=true;$('#feedback').textContent=`${question.fact} — the trap strikes! One heart lost.`;setTimeout(()=>trapResolve(false),1400)}return}if(ok){stats.kCorrect++;awardGoldenRings();b.classList.add('correct');if(!knowledgeLearned.has(question.id)){knowledgeLearned.add(question.id);saveKnowledge();updateKnowHud()}stats.score+=150;$('#score').textContent=`★ ${stats.score}`;$('#feedback').textContent=`✔ ${question.fact}`;const wasGate=challengeMode==='gate-knowledge';setTimeout(()=>{modal('#mathPanel',false);$('#answers').classList.remove('know');$('#qIcon').innerHTML='';if(wasGate){world.gateOpen=true;challengeMode='gate';paused=false;celebrateUntil=performance.now()+1200;caption('Knowledge lights the way — the gate opens!')}else{if(activeCore)activeCore.done=true;activeCore=null,activeTrap=null;paused=false;celebrateUntil=performance.now()+900;caption(`Data Core learned: ${question.fact}`)}},1000)}else{b.classList.add('wrong');b.disabled=true;$('#feedback').textContent=`Not quite — ${question.fact} Try another option.`}}
const TRAP_LABEL={thorns:'CRYSTAL THORNS',lava:'VOLCANIC BLAST',trap:'TEMPLE TRAP',pit:'PIT RESCUE'};
function beginTrapChallenge(trap){activeTrap=trap;challengeMode='trap';paused=true;player.vx=0;$('#challengeLabel').textContent=TRAP_LABEL[trap.kind]||'TRAP';if(Math.random()<0.5){question=makeKnowledgeQuestion(new Set([...knowledgeSeen]));knowledgeSeen.add(question.id);paintKnowledge();$('#progress').textContent=`${TRAP_LABEL[trap.kind]} — answer to escape!`}else{$('#qIcon').innerHTML='';$('#answers').classList.remove('know');const cap=Math.min(selectedStage.difficulty[0],maxForGrade(+$('select').value));question=makeQuestion(selectedStage.operation,cap);$('#question').textContent=question.prompt;$('#progress').textContent=`${TRAP_LABEL[trap.kind]} — answer to escape!`;$('#hint').textContent='';const box=$('#answers');box.innerHTML='';question.choices.forEach(v=>{const b=document.createElement('button');b.textContent=v;b.onclick=()=>answer(v,b);box.append(b)})}$('#feedback').textContent='Answer correctly to leap clear — a wrong answer costs a heart!';modal('#mathPanel',true);caption('A trap springs! Think fast!')}
function trapResolve(ok){modal('#mathPanel',false);$('#answers').classList.remove('know');$('#qIcon').innerHTML='';challengeMode='gate';if(ok){const trap=activeTrap,forward=(player.facing||1)>=0;if(trap?.safePoint){player.x=trap.safePoint.x;player.y=trap.safePoint.y}else if(trap)player.x=escapeTrapX(player,trap,world.level.width);else player.x=Math.max(0,Math.min(world.level.width-player.w,player.x+120*(forward?1:-1)));player.invincible=2.4;player.vy=trap?.safePoint?0:-260;player.vx=trap?.safePoint?0:forward?120:-120;activeTrap=null;paused=false;celebrateUntil=performance.now()+900;caption('Clear! Mahi lands safely beyond the trap.')}else{if(!loseLife())return;const samePoint=activeTrap?.safePoint||{x:player.x-20*(player.facing||1),y:player.y};player.hurt(samePoint);const rescuedFromPit=!!activeTrap?.safePoint;activeTrap=null;paused=false;caption(rescuedFromPit?'One heart lost — Mahi is rescued from the pit.':'One heart lost — Mahi continues from the same point.')}}
const CUSTOM_KEY='mahi-custom-questions',CHEAT_OPS={'+':'addition','-':'subtraction','x':'multiplication','×':'multiplication','*':'multiplication','/':'division','÷':'division',':':'division'};
function loadCustomQuestions(){try{return JSON.parse(localStorage.getItem(CUSTOM_KEY))||[]}catch{return[]}}
function saveCustomQuestion(a,operation,b){const bank=loadCustomQuestions(),key=`${a}|${operation}|${b}`;if(bank.some(q=>`${q.a}|${q.operation}|${q.b}`===key))return bank;bank.push({a,operation,b});localStorage.setItem(CUSTOM_KEY,JSON.stringify(bank));return bank}
function pickCustomQuestion(operation){const bank=loadCustomQuestions().filter(q=>operation==='mixed'||q.operation===operation);if(!bank.length)return null;const c=bank[Math.floor(Math.random()*bank.length)];try{return makeCustomQuestion(c.a,c.operation,c.b)}catch{return null}}
function cheatManualQuestion(){const raw=prompt('Cheat — enter a question to use now and save for later (e.g. "7 x 8", "45 / 9", "12 + 5"):');if(!raw)return;const m=raw.trim().match(/^(\d+)\s*([+\-x×*/÷:])\s*(\d+)$/i);if(!m){caption('Cheat: could not read that. Try like "7 x 8".');return}const q=makeCustomQuestion(+m[1],CHEAT_OPS[m[2].toLowerCase()],+m[3]),bank=saveCustomQuestion(q.a,q.operation,q.b);if($('#mathPanel').classList.contains('hidden')){caption(`Cheat question saved • ${bank.length} in the bank. It will resurface in future challenges.`);return}question=q;$('#question').textContent=q.prompt;$('#hint').textContent='';$('#feedback').textContent=`Cheat question loaded • ${bank.length} saved for later.`;const box=$('#answers');box.innerHTML='';q.choices.forEach(v=>{const b=document.createElement('button');b.textContent=v;b.onclick=()=>answer(v,b);box.append(b)});}
function stageOpponent(){return world.level.enemies.find(e=>e.stage===selectedStage.id)}
function updateEnemies(dt){const e=stageOpponent();if(!e||e.cleared)return;e.x+=e.vx*dt;if(e.x<e.minX||e.x>e.maxX){e.vx*=-1;e.x=Math.max(e.minX,Math.min(e.maxX,e.x))}const insideMandatoryZone=player.x+player.w>=e.minX-45&&player.x<=e.maxX+45;if(insideMandatoryZone&&!paused){player.x=Math.min(player.x,e.minX-46-player.w);player.vx=0;beginSentinelChallenge(e)}}
function update(dt){updateEnemies(dt);const input={axis:(keys.ArrowRight||keys.KeyD||keys.right?1:0)-(keys.ArrowLeft||keys.KeyA||keys.left?1:0),jump:!!(keys.Space||keys.ArrowUp||keys.KeyW||keys.jump||keys.up),climb:!!(keys.ArrowUp||keys.KeyW||keys.jump||keys.up),descend:!!(keys.ArrowDown||keys.KeyS||keys.down),run:!!(keys.ShiftLeft||keys.ShiftRight)};player.update(dt,input,world);keys.jump=false;world.updateLoose(player,dt);const nowT=performance.now()/1000;if(player.y>560&&!paused){beginTrapChallenge({kind:'pit',x:player.x-10,y:540,w:player.w+20,h:80,safePoint:{x:checkpoint.x,y:checkpoint.y}});return}else if(!player.invincible){const trap=world.dangerAt(player,nowT);if(trap){beginTrapChallenge(trap);return}}if(!checkpointLit&&Math.abs(player.x-world.level.checkpoint.x)<45){checkpoint=world.level.checkpoint;checkpointLit=true;caption('Checkpoint lit — progress saved.');localStorage.setItem('luma-checkpoint','lit')}world.level.collectibles.forEach((c,i)=>{if(!collected.has(i)&&Math.hypot(player.x-c.x,player.y-c.y)<45){collected.add(i);$('#gems').textContent=`✦ ${collected.size} / 3`;caption('Memory spark found!')}});for(const core of world.level.cores||[]){if(!core.done&&Math.hypot(player.x-core.x,player.y-core.y)<54){beginKnowledgeChallenge(core);break}}const opponent=stageOpponent();if(!world.gateOpen&&opponent?.cleared&&player.x>world.level.gate.x-90&&!paused)beginMath();if(!opponent?.cleared&&player.x>opponent.maxX){player.x=opponent.minX-46-player.w;player.vx=0;caption(`You must answer ${opponent.name} before passing.`)}if(world.gateOpen&&opponent?.cleared&&player.x>world.level.exit.x){paused=true;const sec=Math.round((performance.now()-stats.start)/1000),accuracy=Math.round(stats.correct/stats.attempts*100);$('#completeTitle').textContent=`Stage ${selectedStage.id} complete!`;$('#report').textContent=`${selectedStage.name} • Accuracy: ${accuracy}% • ${stats.attempts} attempts • ${sec} seconds • ${stats.score} points • Best streak ${stats.bestStreak} • 🧠 ${stats.kCorrect} facts this stage (${knowledgeLearned.size}/${KNOWLEDGE_TOTAL} learned)`;$('#nextBtn').style.display=selectedStage.id<10?'inline-block':'none';modal('#complete',true);localStorage.setItem(`luma-stage-${selectedStage.id}`,JSON.stringify({...stats,time:sec,accuracy,complete:true}));localStorage.removeItem(SAVE_KEY)}camera=Math.max(0,Math.min(world.level.width-canvas.width,player.x-360))}
function drawMahi(){for(const e of world.level.enemies){if(e.stage!==selectedStage.id||e.cleared)continue;const laughing=performance.now()<e.laughUntil,bob=laughing?Math.sin(performance.now()/65)*7:0,advanced=['frost','storm','beetle','voidcat'].includes(e.kind),isSentinel=e.kind==='sentinel',sheet=advanced?advancedSprite:isSentinel?sentinelSprite:villainSprite,cells=isSentinel?4:8,advancedOffsets={frost:0,storm:2,beetle:4,voidcat:6},offset=advanced?advancedOffsets[e.kind]:e.kind==='golem'?4:0,frame=advanced?offset+(Math.floor(performance.now()/260)%2):offset+(laughing?3:1+Math.floor(performance.now()/180)%2);if(sheet.complete&&sheet.naturalWidth){const sw=sheet.naturalWidth/cells,size=e.kind==='golem'||e.kind==='beetle'?98:86;ctx.save();ctx.shadowColor=selectedStage.environment.glow;ctx.shadowBlur=12+selectedStage.id;const pulse=advanced&&laughing?1.12:1;if(e.vx<0){ctx.translate(e.x+e.w/2,0);ctx.scale(-1,1);ctx.translate(-(e.x+e.w/2),0)}ctx.drawImage(sheet,frame*sw,0,sw,sheet.naturalHeight,e.x-(size*pulse-e.w)/2,e.y-(size*pulse-e.h)+bob,size*pulse,size*pulse);ctx.restore()}else{ctx.fillStyle='#553c78';ctx.fillRect(e.x,e.y+bob,e.w,e.h)}for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(e.x+4+i*13,e.y-40,5,0,7);ctx.fillStyle=i<e.lights?'#7efff2':'#38425e';ctx.fill();ctx.strokeStyle='#eaffff';ctx.stroke()}}const lx=player.x+player.w/2-25,ly=player.y-46;for(let i=0;i<MAX_LIVES;i++){ctx.beginPath();ctx.arc(lx+i*13,ly,5,0,7);ctx.fillStyle=i<stats.lives?'#ff7187':'#38425e';ctx.fill();ctx.lineWidth=1;ctx.strokeStyle='#ffd7de';ctx.stroke()}
 const frameWidth=mahiSprite.naturalWidth/8,frames={idle:0,run:Math.floor(performance.now()/130)%2?1:2,jump:3,fall:4,climb:5,hurt:6,celebrate:7};let state=performance.now()<celebrateUntil?'celebrate':player.invincible?'hurt':player.state,frame=frames[state]??0;if(!mahiSprite.complete||!mahiSprite.naturalWidth){ctx.fillStyle='#28b7ad';ctx.fillRect(player.x-5,player.y-18,38,70);return}ctx.save();const drawX=player.x-22,drawY=player.y-30;if(player.facing<0){ctx.translate(player.x+player.w/2,0);ctx.scale(-1,1);ctx.translate(-(player.x+player.w/2),0)}ctx.drawImage(mahiSprite,frame*frameWidth,0,frameWidth,mahiSprite.naturalHeight,drawX,drawY,72,96);ctx.restore()}
function updateStageProgress(){const percent=Math.max(0,Math.min(100,Math.round(player.x/Math.max(1,world.level.exit.x)*100)));$('#progressFill').style.width=`${percent}%`;$('#progressLabel').textContent=`Stage ${selectedStage.id} • ${percent}%`;$('#stageProgress').setAttribute('aria-label',`Stage ${selectedStage.id}, ${percent} percent complete`)}
function draw(){
 updateStageProgress();
 const theme=selectedStage.environment,g=ctx.createLinearGradient(0,0,0,540);g.addColorStop(0,theme.sky1);g.addColorStop(1,theme.sky2);ctx.fillStyle=g;ctx.fillRect(0,0,960,540);ctx.save();ctx.translate(-camera,0);
 for(let x=0;x<world.level.width;x+=190){ctx.fillStyle=selectedStage.id===1?'#274f55':selectedStage.id===2?'#26355a':selectedStage.id===3?'#59313d':selectedStage.id>=8?'#211744':'#26355a';ctx.beginPath();if(selectedStage.id===1){ctx.arc(x+60,125,50,Math.PI,0);ctx.lineTo(x+110,210);ctx.lineTo(x+10,210)}else if(selectedStage.id===2){ctx.rect(x+15,65,95,145)}else if(selectedStage.id===3||selectedStage.id===7){ctx.moveTo(x+10,210);ctx.lineTo(x+60,65);ctx.lineTo(x+110,210)}else if(selectedStage.id>=8){ctx.moveTo(x+10,200);ctx.lineTo(x+60,45);ctx.lineTo(x+110,200);ctx.closePath()}else ctx.arc(x+60,115,45,0,7);ctx.fill();ctx.strokeStyle=theme.glow;ctx.stroke()}
 for(const p of world.level.platforms){ctx.fillStyle=theme.stone;ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle=theme.edge;ctx.fillRect(p.x,p.y,p.w,8)}
 for(const c of world.level.climbs||[]){if(c.kind==='ladder'){ctx.strokeStyle=theme.edge;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(c.x+5,c.y);ctx.lineTo(c.x+5,c.y+c.h);ctx.moveTo(c.x+c.w-5,c.y);ctx.lineTo(c.x+c.w-5,c.y+c.h);ctx.stroke();ctx.lineWidth=3;for(let ry=c.y+12;ry<c.y+c.h;ry+=16){ctx.beginPath();ctx.moveTo(c.x+2,ry);ctx.lineTo(c.x+c.w-2,ry);ctx.stroke()}}else{const n=5,sw=c.w/n,sh=c.h/n;for(let k=0;k<n;k++){const x0=c.x+k*sw,y0=c.y+(n-1-k)*sh;ctx.fillStyle=theme.stone;ctx.fillRect(x0,y0,c.w-k*sw,c.h-(n-1-k)*sh);ctx.fillStyle=theme.edge;ctx.fillRect(x0,y0,c.w-k*sw,5)}}}
 for(const h of world.level.hazards){ctx.fillStyle=selectedStage.id===3?'#ffb13b':'#ff6680';for(let x=h.x;x<h.x+h.w;x+=14){ctx.beginPath();ctx.moveTo(x,h.y+h.h);ctx.lineTo(x+7,h.y);ctx.lineTo(x+14,h.y+h.h);ctx.fill()}}
 {const vt=performance.now()/1000;for(const v of world.level.volcanoes||[]){ctx.fillStyle='#39231f';ctx.beginPath();ctx.moveTo(v.x-v.r*1.8,v.y+10);ctx.lineTo(v.x-v.r*0.55,v.y-v.r);ctx.lineTo(v.x+v.r*0.55,v.y-v.r);ctx.lineTo(v.x+v.r*1.8,v.y+10);ctx.closePath();ctx.fill();ctx.fillStyle='#7a3b26';ctx.fillRect(v.x-v.r*1.8,v.y+6,v.r*3.6,6);ctx.fillStyle='#ff7a33';ctx.fillRect(v.x-v.r*0.55,v.y-v.r-3,v.r*1.1,6);const lh=world.lavaColumn(v,vt);if(lh>3){const top=v.y-v.r-lh,gl=ctx.createLinearGradient(0,top,0,v.y-v.r);gl.addColorStop(0,'#fff0a0');gl.addColorStop(.5,'#ff8c3b');gl.addColorStop(1,'#ff3b1f');ctx.save();ctx.shadowColor='#ff8c3b';ctx.shadowBlur=18;ctx.fillStyle=gl;ctx.fillRect(v.x-9,top,18,lh);ctx.restore();ctx.fillStyle='#ffd25a';for(let s=0;s<6;s++){const px=v.x+Math.sin(vt*6+s*1.7)*v.r*1.3,py=top-((vt*240+s*70)%150);ctx.fillRect(px,py,3,3)}}}}
 {const tt=performance.now()/1000;
  for(const s of world.level.spikes||[]){const o=world.spikeOut(s,tt),h=s.h*o;ctx.fillStyle='#3a4150';ctx.fillRect(s.x-3,s.y+s.h-4,s.w+6,4);if(h>1){ctx.fillStyle=o>.55?'#eef2f8':'#8b93a3';for(let x=s.x+2;x<s.x+s.w-3;x+=10){ctx.beginPath();ctx.moveTo(x,s.y+s.h);ctx.lineTo(x+5,s.y+s.h-h);ctx.lineTo(x+10,s.y+s.h);ctx.fill()}}}
  for(const b of world.level.blades||[]){const f=world.bladeOut(b,tt),bh=b.h*f;ctx.fillStyle='#2a2f3a';ctx.fillRect(b.x-b.w/2-4,b.y-8,b.w+8,8);if(bh>2){ctx.fillStyle='#c9d3e6';ctx.beginPath();ctx.moveTo(b.x-b.w/2,b.y);ctx.lineTo(b.x+b.w/2,b.y);ctx.lineTo(b.x+b.w/2,b.y+bh-8);ctx.lineTo(b.x,b.y+bh);ctx.lineTo(b.x-b.w/2,b.y+bh-8);ctx.closePath();ctx.fill();ctx.fillStyle='#7f8aaa';ctx.fillRect(b.x-2,b.y,4,Math.max(0,bh-8))}}
  for(const tl of world.level.looseTiles||[]){if(tl.state==='gone')continue;const shake=tl.state==='shaking'?Math.sin(tt*60)*2:0;ctx.fillStyle=tl.state==='idle'?theme.stone:'#b5714a';ctx.fillRect(tl.x+shake,tl.y,tl.w,tl.h);ctx.fillStyle=theme.edge;ctx.fillRect(tl.x+shake,tl.y,tl.w,4);ctx.strokeStyle='#0006';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(tl.x+tl.w*0.4+shake,tl.y);ctx.lineTo(tl.x+tl.w*0.48+shake,tl.y+tl.h);ctx.moveTo(tl.x+tl.w*0.7+shake,tl.y);ctx.lineTo(tl.x+tl.w*0.63+shake,tl.y+tl.h);ctx.stroke()}
 }
 world.level.collectibles.forEach((c,i)=>{if(!collected.has(i)){ctx.fillStyle='#ffe16b';ctx.beginPath();ctx.arc(c.x,c.y,10,0,7);ctx.fill()}});for(const core of world.level.cores||[]){if(core.done)continue;const pz=1+Math.sin(performance.now()/300)*0.12,cy=core.y+Math.sin(performance.now()/500)*4;ctx.save();ctx.shadowColor='#8ad9ff';ctx.shadowBlur=14;ctx.fillStyle='#8ad9ff';ctx.strokeStyle='#eaffff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(core.x,cy-13*pz);ctx.lineTo(core.x+12*pz,cy);ctx.lineTo(core.x,cy+13*pz);ctx.lineTo(core.x-12*pz,cy);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();ctx.fillStyle='#05263a';ctx.font='bold 14px Georgia,serif';ctx.textAlign='center';ctx.fillText('?',core.x,cy+5);ctx.textAlign='left'}ctx.fillStyle=theme.glow;ctx.fillRect(world.level.checkpoint.x,world.level.checkpoint.y,8,80);ctx.beginPath();ctx.arc(world.level.checkpoint.x+4,world.level.checkpoint.y,14,0,7);ctx.fill();if(!world.gateOpen){ctx.fillStyle='#d28cff';ctx.fillRect(world.level.gate.x,world.level.gate.y,world.level.gate.w,world.level.gate.h);ctx.fillStyle='#fff';ctx.font='22px sans-serif';ctx.fillText(selectedStage.operation==='multiplication'?'×':selectedStage.operation==='addition'?'+':'−',world.level.gate.x+8,410)}drawMahi();ctx.restore();if(paused&&!question&&!$('#settings').classList.contains('hidden')){}else if(paused&&$('#mathPanel').classList.contains('hidden')&&$('#complete').classList.contains('hidden')){ctx.fillStyle='#0009';ctx.fillRect(0,0,960,540);ctx.fillStyle='white';ctx.font='36px sans-serif';ctx.fillText('Paused',420,270)}}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;if(!paused)update(dt);draw();requestAnimationFrame(loop)}
if(sessionStorage.getItem('mahi-adventure'))startStage();
