import { clean, number, pickleString, table } from "@/lib/material-models/pickle-utils";

export function abaqusLibraryFileName(projectName) {
  return `${clean(projectName, "Steel_Project")}_materials.lib`;
}

// Same Abaqus 2020 CAE library envelope as the CDP Calculator's export (see
// lib/cdp-studio/abaqus-library.js) — only the embedded material behavior
// dict differs (elastic + plastic instead of elastic + concreteDamagedPlasticity).
// Unlike that one, this hasn't been verified against a CAE-created reference
// file yet; test-import before relying on it.
export function generateAbaqus2020Library(inputs, model, projectName) {
  const materialName = clean(inputs.name, "Steel_Material");
  const fileName = abaqusLibraryFileName(projectName);
  const hardeningTable = table(model.hardening, (point) => point.stress);
  const density = inputs.density * 1e-12;
  const data = `{'plastic': {'temperatureDependency': OFF, 'hardening': ISOTROPIC, 'table': ${hardeningTable}, 'rate': OFF, 'dependencies': 0}, 'materialIdentifier': '', 'description': 'Generated by JSCR Steel Calculator; N-mm-MPa-tonne units', 'density': {'temperatureDependency': OFF, 'dependencies': 0, 'table': ((${number(density)},),), 'distributionType': UNIFORM, 'fieldName': ''}, 'elastic': {'temperatureDependency': OFF, 'moduli': LONG_TERM, 'noCompression': OFF, 'noTension': OFF, 'dependencies': 0, 'table': ((${number(inputs.E)}, ${number(inputs.nu)}),), 'type': ISOTROPIC}, 'name': '${materialName}'}`;
  const now = Date.now() / 1000;

  return `((I0\nI-1\n${pickleString(fileName)}I0\n(dp0\ntp1\n(I1\nI0\n${pickleString(materialName)}I1\n(dp2\n${pickleString("Data Source")}${pickleString("Generated by JSCR Steel Calculator")}s${pickleString("Description")}${pickleString("Generated steel material; N-mm-MPa-tonne units")}s${pickleString("Time Stamp")}F${now}\ns${pickleString("visible")}(lp3\n${pickleString("Data Source")}a${pickleString("Description")}a${pickleString("Units")}a${pickleString("Vendor material name")}as${pickleString("version")}${pickleString("2020")}s${pickleString("Vendor material name")}${pickleString(materialName)}s${pickleString("Units")}${pickleString("N, mm, MPa, tonne")}s${pickleString("Data")}${pickleString(data)}stp4\ntp5\n.`;
}
