"use client";

import { useEffect, useState } from "react";
import { Boxes, Download, Info, Trash2 } from "lucide-react";
import { listMaterials, removeMaterial } from "@/lib/material-models/library-store";
import { combinedLibraryFileName, generateCombinedAbaqus2020Library } from "@/lib/material-models/pickle-utils";
import { generate as generateCDP } from "@/lib/cdp-studio/model";
import {
  abaqusLibraryFileName as cdpLibraryFileName,
  buildMaterialData as buildCDPData,
  generateAbaqus2020Library as cdpLibrary,
} from "@/lib/cdp-studio/abaqus-library";
import { generate as generateSteel } from "@/lib/steel-studio/model";
import {
  abaqusLibraryFileName as steelLibraryFileName,
  buildMaterialData as buildSteelData,
  generateAbaqus2020Library as steelLibrary,
} from "@/lib/steel-studio/abaqus-library";

const KIND_LABEL = { cdp: "CDP", steel: "Steel" };

function saveFile(content, fileName, type = "text/plain") {
  const a = document.createElement("a");
  const url = URL.createObjectURL(new Blob([content], { type }));
  a.href = url;
  a.download = fileName;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

function materialCard(entry) {
  if (entry.kind === "cdp") return generateCDP(entry.inputs);
  return generateSteel(entry.inputs);
}

function materialData(entry) {
  const model = materialCard(entry);
  return entry.kind === "cdp" ? buildCDPData(entry.inputs, model) : buildSteelData(entry.inputs, model);
}

function downloadInp(entry) {
  const model = materialCard(entry);
  saveFile(model.text, `${entry.inputs.name}.inp`);
}

function downloadLib(entry) {
  const model = materialCard(entry);
  const projectName = entry.inputs.name;
  if (entry.kind === "cdp") {
    saveFile(cdpLibrary(entry.inputs, model, projectName), cdpLibraryFileName(projectName), "application/octet-stream");
  } else {
    saveFile(steelLibrary(entry.inputs, model, projectName), steelLibraryFileName(projectName), "application/octet-stream");
  }
}

function downloadAll(materials) {
  const entries = materials.map((entry) => ({
    name: entry.inputs.name,
    dataString: materialData(entry),
    description: `Generated by JSCR ${KIND_LABEL[entry.kind] || entry.kind} Calculator; N-mm-MPa-tonne units`,
  }));
  const fileName = combinedLibraryFileName("JSCR_Materials");
  saveFile(generateCombinedAbaqus2020Library(entries, fileName), fileName, "application/octet-stream");
}

export function MaterialLibraryPanel() {
  const [materials, setMaterials] = useState([]);
  const [downloadedAll, setDownloadedAll] = useState(false);

  useEffect(() => {
    setMaterials(listMaterials());
  }, []);

  function handleRemove(id) {
    removeMaterial(id);
    setMaterials(listMaterials());
  }

  function handleDownloadAll() {
    downloadAll(materials);
    setDownloadedAll(true);
    setTimeout(() => setDownloadedAll(false), 2000);
  }

  return (
    <div className="mt-8 rounded-xl border border-slate-200 bg-white p-6 shadow-card dark:border-slate-800 dark:bg-slate-900">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <Boxes className="text-accent" size={20} />
          <h3 className="text-lg font-extrabold text-primary dark:text-white">Your Material Library</h3>
        </div>
        <button
          type="button"
          onClick={handleDownloadAll}
          disabled={materials.length === 0}
          className="inline-flex items-center gap-1.5 rounded-md bg-primary px-4 py-2 text-xs font-bold text-white hover:bg-accent disabled:cursor-not-allowed disabled:opacity-50"
        >
          <Download size={14} /> {downloadedAll ? "Downloaded" : "Download all materials"}
        </button>
      </div>
      <p className="mt-1.5 text-sm text-slate-500 dark:text-slate-400">
        Materials you save from the CDP or Steel Calculator with "Add to Library" show up here — saved locally in
        your browser, nothing is uploaded.
      </p>
      {materials.length > 0 && (
        <div className="mt-4 flex items-start gap-2 rounded-md border border-cyan-200 bg-cyan-50 p-3 text-xs leading-5 text-primary dark:border-cyan-900 dark:bg-cyan-950 dark:text-cyan-100">
          <Info size={15} className="mt-0.5 shrink-0" />
          <span>
            "Download all materials" bundles everything below into one Abaqus 2020 material-library file — built to
            match a real multi-material .lib exported from Abaqus/CAE, but still worth a test-import before relying
            on it for production work.
          </span>
        </div>
      )}

      {materials.length === 0 ? (
        <p className="mt-5 text-sm text-slate-400">No materials saved yet.</p>
      ) : (
        <div className="mt-5 space-y-2">
          {materials.map((entry) => (
            <div
              key={entry.id}
              className="flex flex-wrap items-center justify-between gap-3 rounded-md border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-950"
            >
              <div className="min-w-0">
                <div className="flex items-center gap-2">
                  <span className="rounded-full bg-cyan-100 px-2 py-0.5 text-[10px] font-extrabold uppercase tracking-wide text-primary dark:bg-cyan-950 dark:text-cyan-100">
                    {KIND_LABEL[entry.kind] || entry.kind}
                  </span>
                  <span className="truncate font-bold text-primary dark:text-white">{entry.inputs.name}</span>
                </div>
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Saved {new Date(entry.savedAt).toLocaleString()}
                </p>
              </div>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => downloadInp(entry)}
                  className="rounded-md border px-2.5 py-1.5 text-xs font-bold text-slate-600 hover:border-accent hover:text-accent dark:border-slate-700 dark:text-slate-300"
                >
                  .inp
                </button>
                <button
                  type="button"
                  onClick={() => downloadLib(entry)}
                  className="rounded-md border px-2.5 py-1.5 text-xs font-bold text-slate-600 hover:border-accent hover:text-accent dark:border-slate-700 dark:text-slate-300"
                >
                  .lib
                </button>
                <button
                  type="button"
                  onClick={() => handleRemove(entry.id)}
                  className="rounded-md p-1.5 text-red-500 hover:bg-red-50 dark:hover:bg-red-950"
                  aria-label="Remove"
                >
                  <Trash2 size={14} />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
